name: Build resume document

on:
  push:
    branches:
      - main

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build resumes
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            resume.typst
            resume_ai.typst
            resume_backend.typst

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}" > sa.json
          cat <<EOF > ~/.config/rclone/rclone.conf
          [gdrive]
          type = drive
          scope = drive
          service_account_file = sa.json
          EOF

      - name: Upload PDFs to Drive
        run: |
          rclone copy . gdrive: --include "*.pdf" --drive-root-folder-id 1s5nmE7KUVCG8ooX-1slN9YfOGapuBft5